export const languages = {
  'auto': 'Auto Detect',
  'af': 'Afrikaans',
  'ay': 'Aymara',
  'sq': 'Albanian',
  'de': 'German',
  'am': 'Amharic',
  'ar': 'Arabic',
  'hy': 'Armenian',
  'as': 'Assamese',
  'az': 'Azerbaijani',
  'bm': 'Bambara',
  'bn': 'Bengali',
  'bho': 'Bhojpuri',
  'be': 'Belarusian',
  'my': 'Burmese',
  'bs': 'Bosnian',
  'bg': 'Bulgarian',
  'km': 'Khmer',
  'kn': 'Kannada',
  'ca': 'Catalan',
  'ceb': 'Cebuano',
  'cs': 'Czech',
  'ny': 'Nyanja',
  'zh-cn': 'Chinese (Simplified)',
  'zh-tw': 'Chinese (Traditional)',
  'si': 'Sinhala',
  'ko': 'Korean',
  'co': 'Corsican',
  'ht': 'Haitian Creole',
  'hr': 'Croatian',
  'da': 'Danish',
  'dv': 'Dhivehi',
  'doi': 'Dogri',
  'sk': 'Slovak',
  'sl': 'Slovenian',
  'es': 'Spanish',
  'eo': 'Esperanto',
  'et': 'Estonian',
  'eu': 'Basque',
  'ee': 'Ewe',
  'fi': 'Finnish',
  'fr': 'French',
  'fy': 'Frisian',
  'gd': 'Scottish Gaelic',
  'cy': 'Welsh',
  'gl': 'Galician',
  'ka': 'Georgian',
  'el': 'Greek',
  'gn': 'Guarani',
  'gu': 'Gujarati',
  'ha': 'Hausa',
  'haw': 'Hawaiian',
  'iw': 'Hebrew',
  'hi': 'Hindi',
  'hmn': 'Hmong',
  'hu': 'Hungarian',
  'ig': 'Igbo',
  'ilo': 'Ilocano',
  'id': 'Indonesian',
  'en': 'English',
  'ga': 'Irish',
  'is': 'Icelandic',
  'it': 'Italian',
  'ja': 'Japanese',
  'jw': 'Javanese',
  'kk': 'Kazakh',
  'rw': 'Kinyarwanda',
  'ky': 'Kirghiz',
  'gom': 'Goan Konkani',
  'kri': 'Krio',
  'ku': 'Kurdish',
  'ckb': 'Central Kurdish',
  'lo': 'Lao',
  'la': 'Latin',
  'lv': 'Latvian',
  'ln': 'Lingala',
  'lt': 'Lithuanian',
  'lg': 'Luganda',
  'lb': 'Luxembourgish',
  'mk': 'Macedonian',
  'mai': 'Maithili',
  'ml': 'Malayalam',
  'ms': 'Malay',
  'mg': 'Malagasy',
  'mt': 'Maltese',
  'mi': 'Māori',
  'mr': 'Marathi',
  'mni-mtei': 'Manipuri',
  'lus': 'Mizo',
  'mn': 'Mongolian',
  'nl': 'Dutch',
  'ne': 'Nepali',
  'no': 'Norwegian',
  'or': 'Odia',
  'om': 'Oromo',
  'pa': 'Punjabi',
  'ps': 'Pashto',
  'fa': 'Persian',
  'pl': 'Polish',
  'pt': 'Portuguese',
  'qu': 'Quechua',
  'ro': 'Romanian',
  'ru': 'Russian',
  'sm': 'Samoan',
  'sa': 'Sanskrit',
  'nso': 'Northern Sotho',
  'sr': 'Serbian',
  'st': 'Southern Sotho',
  'sn': 'Shona',
  'sd': 'Sindhi',
  'so': 'Somali',
  'sw': 'Swahili',
  'sv': 'Swedish',
  'su': 'Sundanese',
  'tl': 'Tagalog',
  'th': 'Thai',
  'ta': 'Tamil',
  'tt': 'Tatar',
  'tg': 'Tajik',
  'te': 'Telugu',
  'ti': 'Tigrinya',
  'ts': 'Tswana',
  'tr': 'Turkish',
  'tk': 'Turkmen',
  'ak': 'Akan',
  'uk': 'Ukrainian',
  'ug': 'Uyghur',
  'ur': 'Urdu',
  'uz': 'Uzbek',
  'vi': 'Vietnamese',
  'xh': 'Xhosa',
  'yi': 'Yiddish',
  'yo': 'Yoruba',
  'zu': 'Zulu'
} as const;

export type LanguageCode = keyof typeof languages;